import type { BotLevel, BotResolvedLevel } from "./types";

export const BOT_LEVELS: Record<BotLevel, BotResolvedLevel> = {
  1: {
    level: 1,
    skillLevel: -9,
    moveTimeMs: 50,
    maxDepth: 5,
    approximateElo: 800,
    recommendedEngine: "fairy-stockfish",
    supportsStandardStockfish: false,
  },
  2: {
    level: 2,
    skillLevel: -5,
    moveTimeMs: 100,
    maxDepth: 5,
    approximateElo: 1100,
    recommendedEngine: "fairy-stockfish",
    supportsStandardStockfish: false,
  },
  3: {
    level: 3,
    skillLevel: -1,
    moveTimeMs: 150,
    maxDepth: 5,
    approximateElo: 1400,
    recommendedEngine: "fairy-stockfish",
    supportsStandardStockfish: false,
  },
  4: {
    level: 4,
    skillLevel: 3,
    moveTimeMs: 200,
    maxDepth: 5,
    approximateElo: 1700,
    recommendedEngine: "stockfish",
    supportsStandardStockfish: true,
  },
  5: {
    level: 5,
    skillLevel: 7,
    moveTimeMs: 300,
    maxDepth: 5,
    approximateElo: 2000,
    recommendedEngine: "stockfish",
    supportsStandardStockfish: true,
  },
  6: {
    level: 6,
    skillLevel: 11,
    moveTimeMs: 400,
    maxDepth: 8,
    approximateElo: 2300,
    recommendedEngine: "stockfish",
    supportsStandardStockfish: true,
  },
  7: {
    level: 7,
    skillLevel: 16,
    moveTimeMs: 500,
    maxDepth: 13,
    approximateElo: 2700,
    recommendedEngine: "stockfish",
    supportsStandardStockfish: true,
  },
  8: {
    level: 8,
    skillLevel: 20,
    moveTimeMs: 1000,
    maxDepth: 22,
    approximateElo: 3000,
    recommendedEngine: "stockfish",
    supportsStandardStockfish: true,
  },
};
